import cv2
import matplotlib.pyplot as plt

image=cv2.imread(r"C:/Users/91981/Documents/others/WIE/Converting_to_pencil_sketch_task1/picture.jpg")
plt.imshow(image[:,:,::-1])
plt.axis(False)
plt.title("Original Image")
plt.show()
grayscale=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
plt.imshow(grayscale,cmap='gray')
plt.axis(False)
plt.title("Grayscale Image")
plt.show()
invert=cv2.bitwise_not(grayscale)
plt.imshow(invert,cmap='gray')
plt.axis(False)
plt.title("Inverted Image")
plt.show()
imgsmooth=cv2.GaussianBlur(invert,(21,21),sigmaX=0,sigmaY=0)
plt.imshow(imgsmooth,cmap='gray')
plt.axis(False)
plt.title("Smoothened Image")
plt.show()
final = cv2.divide(grayscale,255-imgsmooth,scale=255)
plt.imshow(final,cmap='gray')
plt.axis(False)
plt.title("Final Image")
plt.show()